ALTER TABLE "Lead" ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE "Lead" ADD COLUMN "source" TEXT NOT NULL DEFAULT 'other';
ALTER TABLE "Lead" ADD COLUMN "nextFollowUpDate" TEXT NOT NULL DEFAULT '';
