ALTER TABLE "Lead" ADD COLUMN "routeStopOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN "routeCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN "routeNote" TEXT NOT NULL DEFAULT '';
