ALTER TABLE "Lead" ADD COLUMN "showingStatus" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "showingOutcome" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "showingOutcomeNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "showingCompletedAt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Lead" ADD COLUMN "showingCanceledReason" TEXT NOT NULL DEFAULT '';
